#!/bin/bash -e

export

git remote -v

if [[ -z "$1" ]]
then
  echo "An upstream must be passed as the first parameter."
  exit 1
fi

git remote add upstream $1
git fetch upstream --tags
git push origin --tags
